// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using glovers_backstore.Data;

#nullable disable

namespace glovers_backstore.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20240722215304_AddedNutritionAndSeeded")]
    partial class AddedNutritionAndSeeded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("glovers_backstore.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NutritionImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Fruit",
                            Description = "Fresh red apple",
                            Image = "pink_apple.jpg",
                            NutritionImage = "apple.svg",
                            Price = 0.99m,
                            Title = "Apple"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Fruit",
                            Description = "Ripe yellow banana",
                            Image = "bannana.jpg",
                            NutritionImage = "banana.svg",
                            Price = 0.59m,
                            Title = "Banana"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Fruit",
                            Description = "Juicy orange",
                            Image = "orange.jpg",
                            NutritionImage = "orange.svg",
                            Price = 1.19m,
                            Title = "Orange"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Vegetable",
                            Description = "Fresh green broccoli",
                            Image = "brocolli.jpg",
                            NutritionImage = "brocolli.svg",
                            Price = 1.79m,
                            Title = "Broccoli"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Vegetable",
                            Description = "Crunchy orange carrot",
                            Image = "carrot.jpg",
                            NutritionImage = "carrots.svg",
                            Price = 0.89m,
                            Title = "Fresh Carrots"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Vegetable",
                            Description = "Red ripe tomato",
                            Image = "tomato.jpg",
                            NutritionImage = "tomatos.svg",
                            Price = 1.49m,
                            Title = "Pack of 3 Tomatos"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Vegetable",
                            Description = "Starchy brown potato",
                            Image = "potato.jpg",
                            NutritionImage = "potatos.svg",
                            Price = 0.99m,
                            Title = "Baking Potatos"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Bakery",
                            Description = "Whole wheat bread",
                            Image = "bread.jpg",
                            NutritionImage = "bread.svg",
                            Price = 2.49m,
                            Title = "Bread"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Dairy",
                            Description = "Fresh whole milk",
                            Image = "milk.jpg",
                            NutritionImage = "whole_milk.svg",
                            Price = 1.49m,
                            Title = "Whole Milk"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Dairy",
                            Description = "Cheddar cheese block",
                            Image = "cheese.jpg",
                            NutritionImage = "cheddar_cheese.svg",
                            Price = 3.99m,
                            Title = "Cheddar Cheese"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Dairy",
                            Description = "Plain Greek yogurt",
                            Image = "yoghurt.jpg",
                            NutritionImage = "greek_yogurt.svg",
                            Price = 0.99m,
                            Title = "Greek Yogurt"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Meat",
                            Description = "Boneless skinless chicken breast",
                            Image = "chicken-breast.jpg",
                            NutritionImage = "chicken_breast.svg",
                            Price = 4.99m,
                            Title = "Chicken Breast"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Meat",
                            Description = "Juicy beef steak",
                            Image = "beef-steak.jpg",
                            NutritionImage = "beef_steak.svg",
                            Price = 9.99m,
                            Title = "Beef Steak"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Seafood",
                            Description = "Fresh salmon fillet",
                            Image = "salmon-fillet.jpg",
                            NutritionImage = "salmon_fillet.svg",
                            Price = 12.99m,
                            Title = "Salmon Fillet"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Seafood",
                            Description = "Frozen peeled shrimp",
                            Image = "shrimp.jpg",
                            NutritionImage = "frozen_shrimp.svg",
                            Price = 14.99m,
                            Title = "Frozen Shrimp"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Grain",
                            Description = "Whole grain pasta",
                            Image = "pasta.jpg",
                            NutritionImage = "pene_pasta.svg",
                            Price = 1.29m,
                            Title = "Pene Pasta"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Grain",
                            Description = "Long grain rice",
                            Image = "rice.jpg",
                            NutritionImage = "white_rice.svg",
                            Price = 1.09m,
                            Title = "White Rice"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Grain",
                            Description = "Rolled oats",
                            Image = "oats.jpg",
                            NutritionImage = "oats.svg",
                            Price = 2.49m,
                            Title = "Kirkland Oats"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Nuts",
                            Description = "Raw whole almonds",
                            Image = "almonds.jpg",
                            NutritionImage = "almonds.svg",
                            Price = 5.99m,
                            Title = "Kirkland Almonds"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Spreads",
                            Description = "Creamy peanut butter",
                            Image = "peanut-butter.jpg",
                            NutritionImage = "peanut_butter.svg",
                            Price = 3.49m,
                            Title = "Jif Peanut Butter"
                        });
                });

            modelBuilder.Entity("glovers_backstore.Data.Models.ProductReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductReviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The apple was very fresh and juicy, with a perfect balance of sweetness and tartness.",
                            ProductId = 1,
                            Rating = 5,
                            Title = "Delicious and Fresh"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Really enjoyed the crispiness and taste, but it could have been a bit sweeter.",
                            ProductId = 1,
                            Rating = 4,
                            Title = "Great Apple"
                        },
                        new
                        {
                            Id = 3,
                            Description = "It was okay, a bit too ripe for my taste, but still edible.",
                            ProductId = 2,
                            Rating = 3,
                            Title = "Average Banana"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Just the right ripeness, sweet and tasty with no bruises.",
                            ProductId = 2,
                            Rating = 5,
                            Title = "Perfectly Ripe"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Nice and juicy, good flavor, but had a few seeds.",
                            ProductId = 3,
                            Rating = 4,
                            Title = "Juicy Orange"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Very sweet and fresh, loved it. Perfect for snacking.",
                            ProductId = 3,
                            Rating = 5,
                            Title = "Excellent Orange"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Crisp and fresh, perfect for my stir fry. Stayed green and vibrant after cooking.",
                            ProductId = 4,
                            Rating = 5,
                            Title = "Fresh Broccoli"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Good quality, stayed fresh for a while, but some florets were a bit small.",
                            ProductId = 4,
                            Rating = 4,
                            Title = "Good Quality"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Very crunchy and sweet, great for snacking and salads.",
                            ProductId = 5,
                            Rating = 4,
                            Title = "Crunchy Carrots"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Not the best, but still okay. A few were a bit limp.",
                            ProductId = 5,
                            Rating = 3,
                            Title = "Decent Carrots"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Perfectly ripe and juicy tomatoes, ideal for sandwiches and salads.",
                            ProductId = 6,
                            Rating = 5,
                            Title = "Ripe Tomatoes"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Nice pack of tomatoes, good for salads, but a couple were a bit soft.",
                            ProductId = 6,
                            Rating = 4,
                            Title = "Good Pack"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Good for baking and mashing, with a nice fluffy texture when cooked.",
                            ProductId = 7,
                            Rating = 4,
                            Title = "Starchy Potatoes"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Some were a bit small, but overall okay for general use.",
                            ProductId = 7,
                            Rating = 3,
                            Title = "Average Potatoes"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Tasty and healthy, loved the texture and flavor, perfect for sandwiches.",
                            ProductId = 8,
                            Rating = 5,
                            Title = "Whole Wheat Bread"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Fresh and soft, very good quality, but could use a bit more fiber.",
                            ProductId = 8,
                            Rating = 4,
                            Title = "Good Bread"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Tastes fresh and creamy, perfect for cereals and drinking straight.",
                            ProductId = 9,
                            Rating = 5,
                            Title = "Fresh Milk"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Nice fresh milk, kids loved it, but a bit pricey.",
                            ProductId = 9,
                            Rating = 4,
                            Title = "Good Milk"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Rich and creamy, great for sandwiches and snacking, with a sharp flavor.",
                            ProductId = 10,
                            Rating = 5,
                            Title = "Cheddar Cheese"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Nice flavor and texture, good for snacks and cooking.",
                            ProductId = 10,
                            Rating = 4,
                            Title = "Good Cheese"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Thick and creamy, perfect for breakfast with honey and nuts.",
                            ProductId = 11,
                            Rating = 4,
                            Title = "Greek Yogurt"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Loved the texture and taste, very fresh and tangy.",
                            ProductId = 11,
                            Rating = 5,
                            Title = "Excellent Yogurt"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Very juicy and tender, great for grilling and stir-fries.",
                            ProductId = 12,
                            Rating = 5,
                            Title = "Juicy Chicken Breast"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Good quality, cooked up nicely, but a bit on the expensive side.",
                            ProductId = 12,
                            Rating = 4,
                            Title = "Good Chicken"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Excellent steak, very juicy and flavorful, perfect for grilling.",
                            ProductId = 13,
                            Rating = 5,
                            Title = "Juicy Beef Steak"
                        },
                        new
                        {
                            Id = 26,
                            Description = "Nice flavor, cooked up well, but slightly tough in some parts.",
                            ProductId = 13,
                            Rating = 4,
                            Title = "Good Steak"
                        },
                        new
                        {
                            Id = 27,
                            Description = "Very fresh and flavorful, great for grilling or baking.",
                            ProductId = 14,
                            Rating = 5,
                            Title = "Fresh Salmon Fillet"
                        },
                        new
                        {
                            Id = 28,
                            Description = "Nice fillet, good taste, but a bit pricey.",
                            ProductId = 14,
                            Rating = 4,
                            Title = "Good Salmon"
                        },
                        new
                        {
                            Id = 29,
                            Description = "Tasty and convenient, easy to cook and perfect for pasta dishes.",
                            ProductId = 15,
                            Rating = 5,
                            Title = "Frozen Shrimp"
                        },
                        new
                        {
                            Id = 30,
                            Description = "Nice flavor, good quality, but a bit too many small ones.",
                            ProductId = 15,
                            Rating = 4,
                            Title = "Good Shrimp"
                        },
                        new
                        {
                            Id = 31,
                            Description = "Good texture and taste, healthy option for pasta dishes.",
                            ProductId = 16,
                            Rating = 4,
                            Title = "Whole Grain Pasta"
                        },
                        new
                        {
                            Id = 32,
                            Description = "Not bad, but I prefer other brands for a more robust flavor.",
                            ProductId = 16,
                            Rating = 3,
                            Title = "Decent Pasta"
                        },
                        new
                        {
                            Id = 33,
                            Description = "Cooks up nicely, good quality rice, perfect for pilafs and side dishes.",
                            ProductId = 17,
                            Rating = 5,
                            Title = "Long Grain Rice"
                        },
                        new
                        {
                            Id = 34,
                            Description = "Nice texture, cooked evenly, but a bit sticky.",
                            ProductId = 17,
                            Rating = 4,
                            Title = "Good Rice"
                        },
                        new
                        {
                            Id = 35,
                            Description = "Perfect for breakfast, very fresh and great for overnight oats.",
                            ProductId = 18,
                            Rating = 5,
                            Title = "Rolled Oats"
                        },
                        new
                        {
                            Id = 36,
                            Description = "Nice quality, good for overnight oats and baking.",
                            ProductId = 18,
                            Rating = 4,
                            Title = "Good Oats"
                        },
                        new
                        {
                            Id = 37,
                            Description = "Crunchy and fresh, perfect snack, and great for adding to salads.",
                            ProductId = 19,
                            Rating = 5,
                            Title = "Raw Almonds"
                        },
                        new
                        {
                            Id = 38,
                            Description = "Nice flavor, good quality, but a few were a bit bitter.",
                            ProductId = 19,
                            Rating = 4,
                            Title = "Good Almonds"
                        },
                        new
                        {
                            Id = 39,
                            Description = "Rich and creamy, perfect for sandwiches and baking. Great taste.",
                            ProductId = 20,
                            Rating = 5,
                            Title = "Creamy Peanut Butter"
                        },
                        new
                        {
                            Id = 40,
                            Description = "Nice and smooth, great for spreading, but a bit too sweet for my liking.",
                            ProductId = 20,
                            Rating = 4,
                            Title = "Tasty Peanut Butter"
                        });
                });

            modelBuilder.Entity("glovers_backstore.Data.Models.ProductReview", b =>
                {
                    b.HasOne("glovers_backstore.Data.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
